import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="bg-gray-100">
                    <Link href="/">
                        <button
                            className="bg-rose-500 hover:bg-red-300 text-white font-bold py-1 px-2 rounded focus:outline-none focus:shadow-outline"
                        >
                            Trang chủ
                        </button>
                    </Link>
                    <div className="text-green-600 font-bold">Đồn Biên phòng CKQT Nậm Cắn</div>
                    <Link href="/admin">
                        <button
                            className="bg-gray-100 hover:bg-green-300 text-black font-bold py-1 px-2 rounded focus:outline-none focus:shadow-outline"
                        >
                            Đăng nhập
                        </button>
                    </Link>
                </header>
                {children}
                <footer className="bg-gray-100 text-red-500">Đ/c: Xã Nậm Cắn, huyện Kỳ Sơn, tỉnh Nghệ An</footer>
            </body>
        </html>
    );
}
