import type {Metadata} from "next";
import {Inter} from "next/font/google";
///import "./globals.css";

const inter = Inter({subsets: ["latin"]});
import x from '@/styles/app.module.css';
import y from '@/styles/header.module.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <header className={x['red']}> Đồn Biên phòng CKQT Nậm Cắn</header>
    {children}
    <footer className={y['red']}>Đ/c: Xã Nậm Cắn, huyện Kỳ Sơn, tỉnh Nghệ An</footer>

    </body>
    </html>
  );
}
