import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <header>
                <Link href="/">
                    <button>Trang chủ</button>
                </Link>
            Đồn Biên phòng CKQT Nậm Cắn

                <Link href="/admin">
                    <button>Đăng nhập</button>
                </Link>

        </header>
        {children}
        <footer>Đ/c: Xã Nậm Cắn, huyện Kỳ Sơn, tỉnh Nghệ An</footer>
        </body>
        </html>
    );
}
